plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.detekt)
    alias(libs.plugins.androidx.baselineprofile)
}

android {
    namespace = "com.compass.app"
    compileSdk = 37

    defaultConfig {
        applicationId = "com.compass.app"
        minSdk = 31
        targetSdk = 37
        versionCode = 37
        versionName = "1.0.36"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
            // WARNING: release APK is signed with the debug keystore for local
            // iteration convenience. Wire a real signingConfig before Play
            // distribution (env-var-backed keystore, or Play App Signing).
            signingConfig = signingConfigs.getByName("debug")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
    }

    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_25)
        }
    }

    // Strong skipping is enabled by default since Compose Compiler 2.0 / Kotlin 2.0
    // (ComposeFeatureFlag.StrongSkipping). No composeCompiler {} override needed.
    // See: https://kotlinlang.org/docs/compose-compiler-options.html

    buildFeatures {
        compose = true
        buildConfig = false
    }

    lint {
        abortOnError = true
        warningsAsErrors = true
        checkDependencies = true
        checkReleaseBuilds = true
        explainIssues = true
        showAll = true
        lintConfig = rootProject.file("config/lint/lint.xml")
    }

    testOptions {
        managedDevices {
            localDevices {
                register("pixel7aApi37") {
                    device = "Pixel 7a"
                    apiLevel = 37
                    systemImageSource = "google"
                    pageAlignment =
                        com.android.build.api.dsl.ManagedVirtualDevice.PageAlignment.FORCE_16KB_PAGES
                    testedAbi = "arm64-v8a"
                }
            }
        }
    }
}

detekt {
    buildUponDefaultConfig = true
    allRules = false
    config.setFrom(rootProject.files("config/detekt/detekt.yml"))
    baseline = rootProject.file("config/detekt/detekt-baseline.xml")
    parallel = true
}

dependencies {
    val composeBom = platform(libs.compose.bom)
    implementation(composeBom)

    implementation(libs.compose.runtime)
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    debugImplementation(libs.compose.ui.tooling)
    implementation(libs.compose.foundation)
    implementation(libs.compose.animation)

    implementation(libs.material3)
    implementation(libs.material3.adaptive)
    implementation(libs.graphics.shapes)

    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    implementation(libs.lifecycle.runtime.compose)

    implementation(libs.datastore.preferences)
    implementation(libs.coroutines.android)

    // Profile installer is what ships the baseline + startup profiles baked into the
    // release AAB. At install / first launch it copies the profiles from the APK
    // into the profile-cache dir that the OS reads when compiling DEX.
    implementation(libs.androidx.profileinstaller)

    // Producer module that regenerates baseline-prof.txt / startup-prof.txt.
    // Required by the androidx.baselineprofile consumer plugin for the release
    // variant (otherwise AGP warns that no profile will be generated).
    baselineProfile(project(":baselineprofile"))

    testImplementation(libs.junit)
    testImplementation(libs.coroutines.test)

    androidTestImplementation(libs.junit)
    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.androidx.test.uiautomator)

    // LeakCanary is debug-only; R8 strips it from release builds. Auto-installs via
    // AppStartup so no manual wiring needed.
    debugImplementation(libs.leakcanary.android)

    detektPlugins(libs.detekt.compose)
    lintChecks(libs.lint.slack.checks)
    lintChecks(libs.lint.slack.compose)
}

// Baseline + startup profiles are regenerated by the :baselineprofile module on the
// pixel7aApi37 managed device via ./build.sh --baseline-profile (not on every
// local assembleRelease - that would require a GMD emulator). saveInSrc writes the
// regenerated baseline-prof.txt + startup-prof.txt into app/src/release/generated/
// so they ship inside the release AAB once CI lands them.
baselineProfile {
    automaticGenerationDuringBuild = false
    saveInSrc = true
}
